set i / 
i1
i2
i3
i4
/

j / 
j1
j2
j3
j4
/

l / 
l1
l2
l3
l4
l5
l6
l7
l8
l9
l10
l11
l12
l13
l14
l15
l16
/;

LI(l,i) = no;
LJ(l,j) = no;

LI( 'l1', 'i1') = yes;
LJ( 'l1', 'j1') = yes;

LI( 'l2', 'i1') = yes;
LJ( 'l2', 'j2') = yes;

LI( 'l3', 'i1') = yes;
LJ( 'l3', 'j3') = yes;

LI( 'l4', 'i1') = yes;
LJ( 'l4', 'j4') = yes;

LI( 'l5', 'i2') = yes;
LJ( 'l5', 'j1') = yes;

LI( 'l6', 'i2') = yes;
LJ( 'l6', 'j2') = yes;

LI( 'l7', 'i2') = yes;
LJ( 'l7', 'j3') = yes;

LI( 'l8', 'i2') = yes;
LJ( 'l8', 'j4') = yes;

LI( 'l9', 'i3') = yes;
LJ( 'l9', 'j1') = yes;

LI( 'l10', 'i3') = yes;
LJ( 'l10', 'j2') = yes;

LI( 'l11', 'i3') = yes;
LJ( 'l11', 'j3') = yes;

LI( 'l12', 'i3') = yes;
LJ( 'l12', 'j4') = yes;

LI( 'l13', 'i4') = yes;
LJ( 'l13', 'j1') = yes;

LI( 'l14', 'i4') = yes;
LJ( 'l14', 'j2') = yes;

LI( 'l15', 'i4') = yes;
LJ( 'l15', 'j3') = yes;

LI( 'l16', 'i4') = yes;
LJ( 'l16', 'j4') = yes;



Parameter
c(l) /
l1  5
l2  4
l3  3
l4  1
l5  1
l6  1
l7  3
l8  5
l9  5
l10  2
l11  1
l12  5
l13  4
l14  1
l15  3
l16  5
/

;
