set i / 
i1
i2
i3
/

j / 
j1
j2
j3
j4
/

l / 
l19
l20
l21
l22
l23
l24
l25
l26
l27
l28
l29
l30
/;

LI(l,i) = no;
LJ(l,j) = no;

LI( 'l19', 'i1') = yes;
LJ( 'l19', 'j1') = yes;

LI( 'l20', 'i1') = yes;
LJ( 'l20', 'j2') = yes;

LI( 'l21', 'i1') = yes;
LJ( 'l21', 'j3') = yes;

LI( 'l22', 'i1') = yes;
LJ( 'l22', 'j1') = yes;

LI( 'l23', 'i2') = yes;
LJ( 'l23', 'j1') = yes;

LI( 'l24', 'i2') = yes;
LJ( 'l24', 'j2') = yes;

LI( 'l25', 'i2') = yes;
LJ( 'l25', 'j3') = yes;

LI( 'l26', 'i2') = yes;
LJ( 'l26', 'j4') = yes;

LI( 'l27', 'i3') = yes;
LJ( 'l27', 'j1') = yes;

LI( 'l28', 'i3') = yes;
LJ( 'l28', 'j2') = yes;

LI( 'l29', 'i3') = yes;
LJ( 'l29', 'j3') = yes;

LI( 'l30', 'i3') = yes;
LJ( 'l30', 'j4') = yes;



Parameter
  A(i) /
i1  20.0
i2  25.0
i3  21.0
/


N(j) /
j1  15.0
j2  17.0
j3  22.0
j4  12.0
/


c(l) /
l19  6.0
l20  2.0
l21  6.0
l22  7.0
l23  4.0
l24  9.0
l25  5.0
l26  3.0
l27  8.0
l28  8.0
l29  1.0
l30  6.0
/

;
